name: Dataset Sync to S3 and EC2

on:
  push:
    branches:
      - dataset 

jobs:
  upload-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1  # change if needed

      - name: Upload dataset to S3
        run: |
          aws s3 sync dataset/ s3://your-bucket-name/dataset/ --delete
          
      - name: Sync dataset from S3 to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Rag-AWS-Deploy
            aws s3 sync s3://your-bucket-name/dataset/ dataset/ --delete
            sudo systemctl restart ragbot.service

