name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            
            # Clone repo if it doesn't exist
            if [ ! -d "/home/ubuntu/Rag-AWS-Deploy" ]; then
              git clone https://github.com/MuhammadSaqlain0978/Rag-AWS-Deploy.git /home/ubuntu/Rag-AWS-Deploy
            fi

            cd /home/ubuntu/Rag-AWS-Deploy
            git reset --hard
            git pull origin main

            # Use Python 3.13 venv (created by Terraform user_data)
            if [ ! -d "venv" ]; then
              /usr/local/bin/python3.13 -m venv venv
            fi

            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Create systemd service if it doesn't exist
            if [ ! -f "/etc/systemd/system/ragbot.service" ]; then
              sudo bash -c 'cat > /etc/systemd/system/ragbot.service <<EOF
              [Unit]
              Description=RAGBot Service
              After=network.target

              [Service]
              User=ubuntu
              WorkingDirectory=/home/ubuntu/Rag-AWS-Deploy
              ExecStart=/home/ubuntu/Rag-AWS-Deploy/venv/bin/python run_server.py
              Restart=always

              [Install]
              WantedBy=multi-user.target
              EOF'
              sudo systemctl daemon-reload
              sudo systemctl enable ragbot.service
            fi

            # Restart service
            sudo systemctl restart ragbot.service
