name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      # Install dependencies (first-time setup safe to rerun)
      sudo apt update -y
      sudo apt install -y python3 python3-pip git

      # Clone repo if it doesn't exist
      if [ ! -d "/home/ubuntu/ragbot" ]; then
        git clone https://github.com/<your-username>/<your-repo>.git /home/ubuntu/ragbot
      fi

      cd /home/ubuntu/ragbot
      git reset --hard
      git pull origin main
      pip3 install -r requirements.txt --user

      # Create systemd service if it doesn't exist
      if [ ! -f "/etc/systemd/system/ragbot.service" ]; then
        sudo bash -c 'cat > /etc/systemd/system/ragbot.service <<EOF
        [Unit]
        Description=RAGBot Service
        After=network.target

        [Service]
        User=ubuntu
        WorkingDirectory=/home/ubuntu/ragbot
        ExecStart=/usr/bin/python3 /home/ubuntu/ragbot/app.py
        Restart=always

        [Install]
        WantedBy=multi-user.target
        EOF'
        sudo systemctl daemon-reload
        sudo systemctl enable ragbot.service
      fi

      # Restart service (works both first-time & updates)
      sudo systemctl restart ragbot.service

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
